# Generated by Django 5.1.6 on 2025-02-26 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafic',
            name='Ime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Svirka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('opis', models.CharField(max_length=300)),
                ('ime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kafic')),
            ],
        ),
    ]
