# Generated by Django 5.1.6 on 2025-02-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_kafic_ime_svirka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafic',
            name='Ime',
            field=models.CharField(default='greska', max_length=30),
        ),
    ]
