# Generated by Django 5.1.6 on 2025-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_kafic_ime'),
    ]

    operations = [
        migrations.AddField(
            model_name='svirka',
            name='proslo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='svirka',
            name='ime',
            field=models.CharField(max_length=40),
        ),
    ]
