# Generated by Django 5.1.6 on 2025-02-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_kafic_ime'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafic',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
