# Generated by Django 5.1.6 on 2025-02-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_kafic_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='svirka',
            name='kafic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='svirke', to='main.kafic'),
        ),
    ]
