# Generated by Django 5.1.6 on 2025-02-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_svirka_kafic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svirka',
            name='datum',
            field=models.DateField(null=True),
        ),
    ]
