# Generated by Django 5.1.6 on 2025-03-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_kafic_iglink_kafic_walink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafic',
            name='iglink',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kafic',
            name='walink',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
