# Generated by Django 5.1.7 on 2025-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_kafic_iglink_alter_kafic_walink'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafic',
            name='adresa',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='kafic',
            name='radno_vreme',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
