# Generated by Django 5.1.7 on 2025-03-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_kafic_iglink_alter_kafic_walink'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafic',
            name='br_mesta',
            field=models.CharField(default='50-100', max_length=1000),
        ),
        migrations.AddField(
            model_name='kafic',
            name='radno_vreme',
            field=models.CharField(default='21:00-01:00', max_length=100),
        ),
    ]
